export const COUNTRIES = [
    { value: 'algeria', label: '🇩🇿 Algeria (+213)' },
    { value: 'angola', label: '🇦🇴 Angola (+244)' },
    { value: 'benin', label: '🇧🇯 Benin (+229)' },
    { value: 'botswana', label: '🇧🇼 Botswana (+267)' },
    { value: 'burkina_faso', label: '🇧🇫 Burkina Faso (+226)' },
    { value: 'burundi', label: '🇧🇮 Burundi (+257)' },
    { value: 'cameroon', label: '🇨🇲 Cameroon (+237)' },
    { value: 'chad', label: '🇹🇩 Chad (+235)' },
    { value: 'congo_drc', label: '🇨🇩 Congo DRC (+243)' },
    { value: 'congo_republic', label: '🇨🇬 Congo Republic (+242)' },
    { value: 'cote_divoire', label: "🇨🇮 Côte d'Ivoire (+225)" },
    { value: 'egypt', label: '🇪🇬 Egypt (+20)' },
    { value: 'ethiopia', label: '🇪🇹 Ethiopia (+251)' },
    { value: 'ghana', label: '🇬🇭 Ghana (+233)' },
    { value: 'guinea', label: '🇬🇳 Guinea (+224)' },
    { value: 'kenya', label: '🇰🇪 Kenya (+254)' },
    { value: 'lesotho', label: '🇱🇸 Lesotho (+266)' },
    { value: 'liberia', label: '🇱🇷 Liberia (+231)' },
    { value: 'madagascar', label: '🇲🇬 Madagascar (+261)' },
    { value: 'malawi', label: '🇲🇼 Malawi (+265)' },
    { value: 'mali', label: '🇲🇱 Mali (+223)' },
    { value: 'mauritius', label: '🇲🇺 Mauritius (+230)' },
    { value: 'morocco', label: '🇲🇦 Morocco (+212)' },
    { value: 'mozambique', label: '🇲🇿 Mozambique (+258)' },
    { value: 'namibia', label: '🇳🇦 Namibia (+264)' },
    { value: 'niger', label: '🇳🇪 Niger (+227)' },
    { value: 'nigeria', label: '🇳🇬 Nigeria (+234)' },
    { value: 'rwanda', label: '🇷🇼 Rwanda (+250)' },
    { value: 'senegal', label: '🇸🇳 Senegal (+221)' },
    { value: 'sierra_leone', label: '🇸🇱 Sierra Leone (+232)' },
    { value: 'south_africa', label: '🇿🇦 South Africa (+27)' },
    { value: 'south_sudan', label: '🇸🇸 South Sudan (+211)' },
    { value: 'sudan', label: '🇸🇩 Sudan (+249)' },
    { value: 'eswatini', label: '🇸🇿 Eswatini (+268)' },
    { value: 'tanzania', label: '🇹🇿 Tanzania (+255)' },
    { value: 'togo', label: '🇹🇬 Togo (+228)' },
    { value: 'tunisia', label: '🇹🇳 Tunisia (+216)' },
    { value: 'uganda', label: '🇺🇬 Uganda (+256)' },
    { value: 'zambia', label: '🇿🇲 Zambia (+260)' },
    { value: 'zimbabwe', label: '🇿🇼 Zimbabwe (+263)' },
    { value: 'other', label: '🌍 Other' }
];

export const MANEB_SUBJECTS = [
    { value: 'agriculture', label: 'Agriculture' },
    { value: 'bible_knowledge', label: 'Bible Knowledge' },
    { value: 'biology', label: 'Biology' },
    { value: 'business_studies', label: 'Business Studies' },
    { value: 'chemistry', label: 'Chemistry' },
    { value: 'chichewa', label: 'Chichewa' },
    { value: 'clothing_textiles', label: 'Clothing & Textiles' },
    { value: 'computer_studies', label: 'Computer Studies' },
    { value: 'creative_arts', label: 'Creative Arts' },
    { value: 'english', label: 'English' },
    { value: 'french', label: 'French' },
    { value: 'geography', label: 'Geography' },
    { value: 'history', label: 'History' },
    { value: 'home_economics', label: 'Home Economics' },
    { value: 'life_skils', label: 'Life Skills' },
    { value: 'mathematics', label: 'Mathematics' },
    { value: 'additional_mathematics', label: 'Additional Mathematics' },
    { value: 'physical_science', label: 'Physical Science' },
    { value: 'physics', label: 'Physics' },
    { value: 'religious_education', label: 'Religious Education / BK' },
    { value: 'social_studies', label: 'Social Studies' },
    { value: 'technical_drawing', label: 'Technical Drawing' },
    { value: 'woodwork', label: 'Woodwork' },
    { value: 'metalwork', label: 'Metalwork' },
    { value: 'other', label: 'Other' }
];

export const APPLICATION_DOCUMENTS = [
    { value: 'passport', label: 'Passport' },
    { value: 'high_school_transcript', label: 'High School Transcript' },
    { value: 'english_proficiency_test', label: 'English Proficiency Test' },
    { value: 'personal_statement', label: 'Personal Statement' },
    { value: 'reference_letter', label: 'Reference Letter' },
    { value: 'cv_or_resume', label: 'CV or Resume' },
    { value: 'portfolio', label: 'Portfolio' },
    { value: 'bank_statement', label: 'Bank Statement' },
    { value: 'motivation_letter', label: 'Motivation Letter' },
    { value: 'medical_certificate', label: 'Medical Certificate' },
    { value: 'passport_photo', label: 'Passport Photo' },
    { value: 'police_clearance', label: 'Police Clearance' }
];
